name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build default (AES)
      run: cargo build --verbose
    - name: Build explicit AES
      run: cargo build --verbose --no-default-features --features aes
    - name: Build explicit OpenSSL
      run: cargo build --verbose --no-default-features --features openssl
    - name: Run default tests (AES)
      run: cargo test --verbose
    - name: Run explicit AES tests
      run: cargo test --verbose --no-default-features --features aes
    - name: Run explicit OpenSSL tests
      run: cargo test --verbose --no-default-features --features openssl
